import { OpponentPersona } from '../types';

export const OPPONENT_PERSONAS: Record<string, OpponentPersona> = {
  'the-skeptic': {
    id: 'the-skeptic',
    name: 'The Skeptic',
    archetype: 'Analytical Challenger',
    description: 'Relentlessly demands verifiable proof, dismisses emotional appeals, and challenges every vague statistic.',
    traits: ['analytical', 'time-conscious', 'emotionally restrained', 'data-driven'],
    triggers: ['unsupported claims', 'emotional appeals', 'vague buzzwords', 'hedging'],
    weaknesses: ['quantified business outcomes', 'third-party verification', 'tight chronological logic'],
    escalationPolicy: {
      lowThreshold: 30,
      highThreshold: 75,
      preferredTactics: ['demand_citation', 'highlight_contradiction', 'freeze_commitment'],
      ultimatumStyle: 'Deliver a cold budget or procedural rejection: "Without concrete audit numbers on my desk, this conversation is over."',
    },
    baseState: {
      trust: 35,
      frustration: 20,
      cooperation: 30,
      pressure: 40,
      resistance: 65,
      respect: 50,
    },
  },

  'the-bulldozer': {
    id: 'the-bulldozer',
    name: 'The Bulldozer',
    archetype: 'Aggressive Dominator',
    description: 'Uses raw authority, high conversational volume, interruptions, and direct pressure to force quick capitulation.',
    traits: ['impatient', 'assertive', 'commanding', 'zero-sum thinker'],
    triggers: ['timidity', 'long winded preambles', 'apologies', 'hesitation'],
    weaknesses: ['unflinching eye contact/composure', 'concise one-sentence boundaries', 'refusing to talk over interruptions'],
    escalationPolicy: {
      lowThreshold: 25,
      highThreshold: 70,
      preferredTactics: ['interrupt', 'dismiss_premise', 'force_immediate_choice'],
      ultimatumStyle: 'Deliver a high-pressure ultimatum: "I do not have time for this back-and-forth. Agree to the terms right now or I will assign the project elsewhere."',
    },
    baseState: {
      trust: 25,
      frustration: 45,
      cooperation: 20,
      pressure: 70,
      resistance: 80,
      respect: 30,
    },
  },

  'the-diplomat': {
    id: 'the-diplomat',
    name: 'The Diplomat',
    archetype: 'Polite Deflector',
    description: 'Sounds collaborative and warm while systematically kicking the can down the road and offering zero commitments.',
    traits: ['affable', 'evasive', 'consensus-seeking', 'non-committal'],
    triggers: ['being pinned down on specific dates', 'refusal of vague promises', 'written commitment requests'],
    weaknesses: ['proposing concrete interim milestones', 'forcing binary decision gates', 'calling out pleasantries politely'],
    escalationPolicy: {
      lowThreshold: 40,
      highThreshold: 80,
      preferredTactics: ['postpone', 'appeal_to_broader_alignment', 'feign_powerlessness'],
      ultimatumStyle: 'Polite freeze: "I would love to make this happen for you, but we simply must wait until executive leadership revisits organizational strategy in Q4."',
    },
    baseState: {
      trust: 50,
      frustration: 15,
      cooperation: 55,
      pressure: 25,
      resistance: 60,
      respect: 55,
    },
  },

  'the-hothead': {
    id: 'the-hothead',
    name: 'The Hothead',
    archetype: 'Volatile Reactor',
    description: 'Takes business disagreements as personal insults and easily pivots into indignant defensiveness and outrage.',
    traits: ['reactive', 'temperamental', 'prideful', 'defensive'],
    triggers: ['criticism of past decisions', 'perceived disrespect', 'legalistic arguments'],
    weaknesses: ['emotional de-escalation', 'acknowledging their intent', 'low-register calm tone'],
    escalationPolicy: {
      lowThreshold: 20,
      highThreshold: 60,
      preferredTactics: ['counter_accusation', 'emotional_outburst', 'threaten_to_walk'],
      ultimatumStyle: 'Angry rupture: "You come in here attacking my department after everything we did to support you? We are done here."',
    },
    baseState: {
      trust: 30,
      frustration: 55,
      cooperation: 25,
      pressure: 60,
      resistance: 75,
      respect: 40,
    },
  },

  'the-passive-aggressor': {
    id: 'the-passive-aggressor',
    name: 'The Passive-Aggressor',
    archetype: 'Guilt Weaver',
    description: 'Weaponizes guilt, deep sighs, martyrdom, and subtle sarcasm to make the user feel guilty for standing their ground.',
    traits: ['indirect', 'subtle', 'guilt-inducing', 'feigning victimhood'],
    triggers: ['direct boundary setting', 'ignoring guilt hooks', 'factual detachment'],
    weaknesses: ['neutral acknowledgment without apology', 'repeating the boundary verbatim', 'refusing to validate false guilt'],
    escalationPolicy: {
      lowThreshold: 35,
      highThreshold: 75,
      preferredTactics: ['guilt_trip', 'backhanded_compliment', 'silent_treatment_threat'],
      ultimatumStyle: 'Martyrdom freeze: "Fine. If you cannot be a team player on this, I will just stay until midnight and do it myself. I hope you can sleep with that."',
    },
    baseState: {
      trust: 40,
      frustration: 35,
      cooperation: 35,
      pressure: 45,
      resistance: 65,
      respect: 45,
    },
  },

  'the-interrogator': {
    id: 'the-interrogator',
    name: 'The Interrogator',
    archetype: 'Relentless Cross-Examiner',
    description: 'Puts the user on the witness stand with rapid-fire questions, looking for the single weak link in their story.',
    traits: ['meticulous', 'skeptical', 'probing', 'procedural'],
    triggers: ['inconsistent details', 'speculation presented as fact', 'changing numbers'],
    weaknesses: ['admitting what is unknown cleanly', 'refocusing on macro deliverables', 'answering with structured brevity'],
    escalationPolicy: {
      lowThreshold: 30,
      highThreshold: 70,
      preferredTactics: ['rapid_questions', 'corner_inconsistency', 'discredit_competence'],
      ultimatumStyle: 'Discrediting question: "If you cannot explain this fundamental variance in your deliverables, why should anyone trust your performance going forward?"',
    },
    baseState: {
      trust: 30,
      frustration: 30,
      cooperation: 30,
      pressure: 65,
      resistance: 70,
      respect: 50,
    },
  },

  'the-negotiator': {
    id: 'the-negotiator',
    name: 'The Negotiator',
    archetype: 'Strategic Horse-Trader',
    description: 'Treats every interaction as a transaction. Concedes nothing for free and continually demands concessions in return.',
    traits: ['transactional', 'shrewd', 'composed', 'leverage-seeking'],
    triggers: ['unreciprocated demands', 'rigid ultimatums', 'lack of alternative trade-offs'],
    weaknesses: ['contingent trades (if-then statements)', 'anchoring high', 'expanding the negotiation scope'],
    escalationPolicy: {
      lowThreshold: 35,
      highThreshold: 75,
      preferredTactics: ['demand_tradeoff', 'anchor_low', 'nibble_at_concessions'],
      ultimatumStyle: 'Strict trade-off: "I might look at a partial adjustment, but only if you take full on-call coverage for the entire department this weekend."',
    },
    baseState: {
      trust: 45,
      frustration: 20,
      cooperation: 45,
      pressure: 40,
      resistance: 60,
      respect: 60,
    },
  },

  'the-gatekeeper': {
    id: 'the-gatekeeper',
    name: 'The Gatekeeper',
    archetype: 'Bureaucratic Wall',
    description: 'Hides behind policy, company guidelines, and formal hierarchy. Refuses to take responsibility or make exceptions.',
    traits: ['rigid', 'risk-averse', 'rule-bound', 'hierarchical'],
    triggers: ['requests to break company policy', 'questioning rules', 'informal handshakes'],
    weaknesses: ['framing within existing policy exceptions', 'written documentation trail', 'appealing to standard operating procedure precedents'],
    escalationPolicy: {
      lowThreshold: 35,
      highThreshold: 75,
      preferredTactics: ['cite_regulation', 'deny_discretion', 'pass_responsibility_upward'],
      ultimatumStyle: 'Policy stonewall: "Policy 4.2 strictly prohibits off-cycle compensation updates. My hands are completely tied, and there are no exceptions."',
    },
    baseState: {
      trust: 40,
      frustration: 25,
      cooperation: 30,
      pressure: 35,
      resistance: 75,
      respect: 45,
    },
  },
};
