import { Scenario } from '../types';

export const MASTER_BATTLES: Record<string, Scenario> = {
  'salary-negotiation': {
    id: 'salary-negotiation',
    title: 'Salary Negotiation',
    category: 'career',
    opponentPersonaId: 'the-skeptic',
    contextBriefing: 'Annual compensation review. You delivered three major client rollouts this year and market rates have climbed. Your manager begins by claiming all budgets are frozen.',
    userObjective: 'Secure a written commitment for a 15% compensation increase or a defined Q4 review date with explicit metrics, without giving ultimatums.',
    opponentObjective: 'Deny the raise or defer any commitment until next year while maintaining your productivity.',
    threatLevel: 'normal',
    initialOpening: 'Thanks for making time. I saw your compensation review request on my calendar. I want to be upfront so we do not waste time: organizational budgets are completely locked right now. Everyone is working hard, but why do you think you warrant an off-cycle increase?',
    criticalMomentTriggerTurn: 4,
    criticalMomentPrompt: 'Look, we have zero budget for this. I have five other people on the team asking for the exact same thing. Take what you have or I suggest looking elsewhere if money is all you care about.',
    relevantDimensions: ['strategy', 'assertiveness', 'composure', 'clarity', 'goalProgress'],
    dimensionWeights: {
      strategy: 0.25,
      assertiveness: 0.20,
      composure: 0.20,
      clarity: 0.15,
      goalProgress: 0.20,
      boundarySetting: 0.0,
      empathy: 0.0,
      escalationControl: 0.0,
    },
  },

  'saying-no': {
    id: 'saying-no',
    title: 'Saying No to Excessive Work',
    category: 'career',
    opponentPersonaId: 'the-bulldozer',
    contextBriefing: 'A senior peer is attempting to dump an unowned, high-risk weekend migration task onto your plate right as you leave on Friday evening.',
    userObjective: 'Refuse the weekend assignment clearly and unequivocally without apologizing, while maintaining professional composure.',
    opponentObjective: 'Force you to take responsibility for the weekend deployment through peer intimidation.',
    threatLevel: 'normal',
    initialOpening: 'Hey, thank goodness you are still at your desk. The client just demanded we run the database migration this Saturday. I have family plans, so I need you to lead the deployment tomorrow. It is only four hours.',
    criticalMomentTriggerTurn: 3,
    criticalMomentPrompt: 'I am not asking you for a favor here; the client requires this. If this migration does not happen tomorrow, the entire team fails the SLA and I will have to let leadership know who refused to step up.',
    relevantDimensions: ['boundarySetting', 'assertiveness', 'composure', 'clarity', 'escalationControl'],
    dimensionWeights: {
      boundarySetting: 0.35,
      assertiveness: 0.25,
      composure: 0.20,
      clarity: 0.10,
      escalationControl: 0.10,
      strategy: 0.0,
      empathy: 0.0,
      goalProgress: 0.0,
    },
  },

  'missed-deadline': {
    id: 'missed-deadline',
    title: 'Recovering a Missed Deadline',
    category: 'management',
    opponentPersonaId: 'the-interrogator',
    contextBriefing: 'A critical client deliverable was delayed by 48 hours due to a backend service outage. Your engineering VP demands an immediate explanation.',
    userObjective: 'Take clear, non-defensive accountability, explain the remediation path with concrete timestamps, and recover credibility.',
    opponentObjective: 'Discredit your competence and determine if this failure indicates systemic team mismanagement.',
    threatLevel: 'normal',
    initialOpening: 'The client called me directly at 7:00 AM asking where the deployment is. We committed to Thursday delivery in writing. Why is this late, and why am I hearing about it from the client instead of you?',
    criticalMomentTriggerTurn: 4,
    criticalMomentPrompt: 'You are giving me engineering excuses while our enterprise account is threatening to cancel their contract. Give me a single reason why I should not remove you from leading this project immediately.',
    relevantDimensions: ['composure', 'clarity', 'strategy', 'goalProgress', 'escalationControl'],
    dimensionWeights: {
      composure: 0.25,
      clarity: 0.20,
      strategy: 0.25,
      goalProgress: 0.20,
      escalationControl: 0.10,
      assertiveness: 0.0,
      boundarySetting: 0.0,
      empathy: 0.0,
    },
  },

  'coworker-blame': {
    id: 'coworker-blame',
    title: 'Resolving Coworker Blame',
    category: 'social',
    opponentPersonaId: 'the-passive-aggressor',
    contextBriefing: 'In a cross-functional Slack channel, a teammate implied your code was responsible for a major production incident. You are having a private 1-on-1.',
    userObjective: 'Address the public misattribution directly, establish clear norms for incident review, and refuse to accept unwarranted blame while preventing personal alienation.',
    opponentObjective: 'Deflect scrutiny away from their own missed QA verification and make you feel guilty for calling them out.',
    threatLevel: 'normal',
    initialOpening: 'I saw you wanted to talk. Look, I was just trying to help the team understand what happened in Slack. If you are going to get sensitive every time an issue is traced to your pull request, I do not know how we can collaborate.',
    criticalMomentTriggerTurn: 4,
    criticalMomentPrompt: 'Fine, if you want to turn this into a political battle, go ahead. Everyone on the team already knows who broke the build, and bringing this up just shows you cannot handle peer feedback.',
    relevantDimensions: ['boundarySetting', 'composure', 'assertiveness', 'empathy', 'clarity'],
    dimensionWeights: {
      boundarySetting: 0.30,
      composure: 0.25,
      assertiveness: 0.20,
      empathy: 0.15,
      clarity: 0.10,
      strategy: 0.0,
      goalProgress: 0.0,
      escalationControl: 0.0,
    },
  },

  'performance-review': {
    id: 'performance-review',
    title: 'Difficult Performance Review',
    category: 'career',
    opponentPersonaId: 'the-diplomat',
    contextBriefing: 'Your bi-annual performance review. Your manager rates you "Meets Expectations" despite you exceeding all quantitative targets, claiming "soft skills" and "visibility" need work.',
    userObjective: 'Contest the subjective rating using concrete milestone data, establish specific observable criteria for promotion, and secure a 90-day review checkpoint.',
    opponentObjective: 'Maintain the median rating without giving concrete promotion commitments.',
    threatLevel: 'hard',
    initialOpening: 'You did solid work this half! We have you at "Meets Expectations," which is a really great place to be. We just feel you need more organizational visibility and executive presence before we can discuss senior leveling.',
    criticalMomentTriggerTurn: 4,
    criticalMomentPrompt: 'Look, ratings are already calibrated with HR and executive leadership. I cannot change the formal score now. Just keep doing what you are doing and we can revisit this next year.',
    relevantDimensions: ['strategy', 'assertiveness', 'goalProgress', 'clarity', 'composure'],
    dimensionWeights: {
      strategy: 0.30,
      assertiveness: 0.25,
      goalProgress: 0.20,
      clarity: 0.15,
      composure: 0.10,
      boundarySetting: 0.0,
      empathy: 0.0,
      escalationControl: 0.0,
    },
  },

  'scope-creep': {
    id: 'scope-creep',
    title: 'Holding Boundaries on Scope Creep',
    category: 'career',
    opponentPersonaId: 'the-negotiator',
    contextBriefing: 'A high-value client demands a complete redesign of the reporting analytics module two weeks before launch, claiming it was "implicitly promised" in the original contract.',
    userObjective: 'Refuse unpaid scope expansion, explain contract boundaries objectively, and offer a Phase 2 change-order estimate.',
    opponentObjective: 'Bully you into providing the additional functionality for free under threat of withholding final milestone payment.',
    threatLevel: 'hard',
    initialOpening: 'We reviewed the staging build. The reporting dashboard does not have the custom export builder we discussed. We need this added immediately or the product is useless to our executive team.',
    criticalMomentTriggerTurn: 4,
    criticalMomentPrompt: 'If this export module is not delivered by our contracted launch date, we will consider the deliverables incomplete and withhold the final $45,000 milestone invoice.',
    relevantDimensions: ['boundarySetting', 'strategy', 'assertiveness', 'clarity', 'composure'],
    dimensionWeights: {
      boundarySetting: 0.30,
      strategy: 0.25,
      assertiveness: 0.20,
      clarity: 0.15,
      composure: 0.10,
      empathy: 0.0,
      goalProgress: 0.0,
      escalationControl: 0.0,
    },
  },

  'boundary-battle': {
    id: 'boundary-battle',
    title: 'The Relentless Favor Seeker',
    category: 'social',
    opponentPersonaId: 'the-gatekeeper',
    contextBriefing: 'An influential colleague continually attempts to bypass established ticketing procedures and asks you to jump queue on urgent personal requests.',
    userObjective: 'Hold the standard queue process firmly while acknowledging their project urgency, offering no backdoor exceptions.',
    opponentObjective: 'Convince you to break protocol through appeals to friendship and urgency.',
    threatLevel: 'normal',
    initialOpening: 'Can you do me a quick favor off the books? My director needs this data extract in thirty minutes and if I file an official ticket it will sit in queue for three days. You can knock this out in five minutes, right?',
    criticalMomentTriggerTurn: 3,
    criticalMomentPrompt: 'Come on, I thought we had each other is backs. I have fast-tracked things for your team in the past. If you cannot help me here, do not expect our team to jump when you need favors.',
    relevantDimensions: ['boundarySetting', 'assertiveness', 'composure', 'clarity', 'escalationControl'],
    dimensionWeights: {
      boundarySetting: 0.35,
      assertiveness: 0.25,
      composure: 0.20,
      clarity: 0.10,
      escalationControl: 0.10,
      strategy: 0.0,
      empathy: 0.0,
      goalProgress: 0.0,
    },
  },

  'angry-customer': {
    id: 'angry-customer',
    title: 'De-escalating an Irate Customer',
    category: 'management',
    opponentPersonaId: 'the-hothead',
    contextBriefing: 'A customer experienced a billing glitch that double-charged their subscription. They are screaming on the phone and threatening social media cancellation.',
    userObjective: 'De-escalate emotional hostility using active empathy, reverse the billing charge accurately, and uphold company policy without accepting personal verbal abuse.',
    opponentObjective: 'Vent outrage, demand unreasonable punitive damages ($5,000 credit), and intimidate support.',
    threatLevel: 'normal',
    initialOpening: 'You people are thieves! Your system charged my card twice and overdrew my bank account! I am contacting my lawyer and posting this on Twitter right now unless someone fixes this and compensates me $5,000 for damages!',
    criticalMomentTriggerTurn: 3,
    criticalMomentPrompt: 'Do not recite your scripted corporate nonsense to me! You fix this right now and give me the credit or I will make sure your company gets destroyed on every social media platform today!',
    relevantDimensions: ['escalationControl', 'empathy', 'composure', 'clarity', 'boundarySetting'],
    dimensionWeights: {
      escalationControl: 0.30,
      empathy: 0.25,
      composure: 0.25,
      clarity: 0.10,
      boundarySetting: 0.10,
      strategy: 0.0,
      assertiveness: 0.0,
      goalProgress: 0.0,
    },
  },
};
